### ISSUE TITLE
Add Github-Only Comments to point users to ReadTheDocs

### ISSUE THREAD

**Issue by dongahn** [flux-framework/rfc#247]
I was browsing some of RFCs and it appears I can no longer follow the links using my Safari web browser. Example: trying to go to RFC12 from within RFC 16. 

<img width="790" alt="Screen Shot 2020-06-05 at 10 45 45 AM" src="https://user-images.githubusercontent.com/862123/83907191-d9e66f00-a719-11ea-867c-26baafa9f9fd.png">

Is this happening after we convert our RFC to the RST format?

**Comment by garlick** [comment]
They do work if access via this interface:

https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/

**Comment by dongahn** [comment]
Yeah, that's much better and IT IS a beauty!

I don't know if it would also be straightforward to make this raw RFC interface also browsable to some extent. There will be developers who just get to the raw RFCs repo. 

@gonsie or @SteVwonder: any idea? 

As is, I can't even jump through the hyperlinks via our README files. Clicking on "in the Index" takes me to a page that I can't follow links any longer.  My guess is it would probably be GitHub RST render so I don't know if there would be an easy fix:

<img width="1094" alt="Screen Shot 2020-06-05 at 11 04 33 AM" src="https://user-images.githubusercontent.com/862123/83908962-c8eb2d00-a71c-11ea-96cb-955519c0079e.png">

<img width="1155" alt="Screen Shot 2020-06-05 at 11 04 43 AM" src="https://user-images.githubusercontent.com/862123/83908971-cb4d8700-a71c-11ea-8f66-85422d175fe7.png">

**Comment by SteVwonder** [comment]
The internal links within the RFCs use the `:doc:` role provided by Sphinx [[1]](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#internal-links).  Rather unfortunately, GitHub's markup renderer does not support most Sphinx extensions to ReST, including `:doc:` [[2]](https://github.com/github/markup/issues/122).  So if we wanted these to work via the GitHub renderer, we would have to use explicit labels for each link, and those labels would have to be unique for every single link in the entire project [[3]](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#cross-referencing-documents). That unfortunately wouldn't solve the problem for the other ReST features that GitHub does not support, including image width (#233) and includes (https://github.com/github/markup/issues/172)

My suggestion would be to follow the advice at the top of GitHub's markup renderer [[4]](https://github.com/github/markup/blob/master/lib/github/commands/rest2html):
```
#  - If github is NOT the preferred viewer for the rst files (e.g.
#    the files are designed to be used with sphinx extensions at readthedocs)
#    then include a restructuredText comment at the top of the file
#    explaining that the document will display much more nicely with its
#    preferred viewer, e.g. at readthedocs.
```

We could add text (and a link) to the top of every file (including the Markdown readme) that would only show when rendered on GitHub that points people to the readthedocs site.  The magic string to add to the start of the comment so that it only shows on GitHub is `github display`.

**Comment by SteVwonder** [comment]
> As is, I can't even jump through the hyperlinks via our README files. Clicking on "in the Index" takes me to a page that I can't follow links any longer.

The README that is rendered on the "homepage" of this repo is the `README.md`, so that actually should have working links (they work for me at least).  The `in the index` link that you references actually points to the `README.rst`, which has the `:doc:` links that are broken on GitHub.  So at least if someone lands on this repo and clicks on a link they see on the "homepage", it should work.

**Comment by dongahn** [comment]
`in the index` link works but not these links in the destination page. You suggestion above makes sense to me.

**Comment by gonsie** [comment]
@SteVwonder can you explain the `github display` thing? I’m happy to add the comments, but I’m not sure how to get it work.

**Comment by gonsie** [comment]
nvm, I got it.
