### ISSUE TITLE
RFC 27: define sched.feasibility RPC

### ISSUE THREAD

**Issue by garlick** [flux-framework/rfc#384]
Problem: the `sched.feasibility` RPC is not defined in an RFC

Consider adding it to [RFC 27:  Flux Resource Allocation Protocol Version 1](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_27.html)

**Comment by grondo** [comment]
This issue came up recently. It becomes awkward to split the feasibility functionality off from the scheduler (e.g. run feasibility checks in a separate module) if feasibility is _required_ to be a subtopic of `sched`.

Perhaps we can define an optional `feasibility` service, with `feasibility.check` or similar (feel free to suggest the appropriate topic string here) defined as the service name for the job feasibility RPC. If a scheduler implements feasibility, then it can register this service name at startup. A separate module, e.g. `sched-fluxion-feasibility` could do the same...

I believe it still makes sense to describe this RPC in [RFC 27](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_27.html).
