### ISSUE TITLE
rfc21: allow jobspec-update event for other top-level keys

### ISSUE THREAD

**Issue by grondo** [flux-framework/rfc#395]
In flux-framework/flux-coral2#92 the jobspec of a job with a DWS spec is modified in place by the dws jobtap plugin.

It would be better to use an RFC 21 `jobspec-update` event to make this modification, but currently RFC 21 forbids updating any keys that do not start with `attributes.`.

I'm not sure the rationale behind limiting `jobspec-update` events to only the `attributes` section of jobspec. Perhaps we can expand this to allow updates to `resources.` as well since there is this use case necessary in flux-coral2?

**Comment by garlick** [comment]
Probably just trying to keep the number of allowed cases to a comprehensible minimum, since the updates aren't signed.  

Seems like it would be ok to update jobspec `resources` since it's just an input to the scheduler, and it's the output of the scheduler (under instance owner control) that determines what happens at run time.

(Sorry now that seems like "duh..." but I needed to talk that through :-)

I can propose a change.
