### ISSUE TITLE
rfc3, rfc12: add uid to messages

### ISSUE THREAD

**Issue by garlick** [flux-framework/rfc#72]
RFC 12 does not currently describe mechanisms used by a multi-user Flux instance, although it includes the statement that users other than the instance owner shall not be allowed to make a direct broker connection.  That is one approach to securing a multi-user instance - requiring new multi-user facing services, connectors, etc. to be implemented that act as secure bridges to internal services.  It is probably not desirable because reserving all "internal" communication to the instance owner unnecessarily partitions the code into "internal" and "external" parts, and may result in duplication of infrastructure like connectors and (likely) poor modularity.

Another approach is to allow other users to connect to the broker, and to add an integer user id field to the base message format (PROTO block, RFC 3).  When a connection is accepted by the connector, some authentication would take place; for example, the local connector uses SO_PEERCRED to authenticate connections.  The uid determined during authentication would be "stamped" on every message flowing from that connection into the broker.

In addition to the uid, we could add a "capability" bitfield to the PROTO block similar to [POSIX capabilities](http://man7.org/linux/man-pages/man7/capabilities.7.html).  At connect time, a user's capabilities could be looked up in an instance table of some kind and set in every message (like the uid above). The equivalent of CAP_SYS_ADMIN could be assigned to the instance owner.   Other capabilities could be added for listing the queue, submitting jobs, killing jobs, etc..

When the broker dispatches requests to services, it could by default require CAP_SYS_ADMIN otherwise return an EPERM response.  Event and response messages lacking CAP_SYS_ADMIN could be dropped.  If a service wants to allow other users "in", they could register additional capabilities with the broker.

I propose to submit PR's to RFC 3 and RFC 10 to implement uids and capabilities in Flux as a first step towards a multi-user security architecture.  Any thoughts?

**Comment by grondo** [comment]
In general this seems like a clean first addition of multi-user functionality to the protocol. I do have some questions, probably more due to my lack of knowledge than any missing pieces in this proposal:

 * How do the instance CURVE keys figure into this plan? I kind of assume that messages would still be encoded with the CURVE key of the instance owner, and the API or other socket providing user access would have access to the key because it is a service running as the instance owner offering access to other users.

 * If capabilities are per user, there is no strict need to have a capability field per *message* right? I can still see the benefits of having a per message capability, since this simplifies code on the *receiving* side, but did you consider and reject the idea of leaving capability lookup as a broker service? (It seems like you made the right choice to me, but it would be interesting to hear the argument against )

> At connect time, a user's capabilities could be looked up in an instance table of some kind and set in every message (like the uid above). The equivalent of CAP_SYS_ADMIN could be assigned to the instance owner. Other capabilities could be added for listing the queue, submitting jobs, killing jobs, etc..

This is good. I think instance owner would allow user's in through some interface in the instance (I'm not sure if you implied this was a per-broker setting, but it seems like it should be global). If a user is not in the access list, then connections would be rejected. Otherwise, no capabilities would be assigned to the connection, but the user may be able to perform the basic query options like you describe: list queues, submit work, list details of their own jobs. For more administrative operations, the user could be assigned new capabilities by the instance owner, but they would have to reconnect.

Is that largely the direction you were thinking?

**Comment by garlick** [comment]
Right now CURVE keys are only used to secure message sent between brokers.  Messages pass in the clear between services, connectors, etc. within a given broker instance.  So yes, I was thinking the instance owner's CURVE keys would still be used in that manner, even when the message originated from another user.  As an aside, a connector that uses CURVE to authenticate and secure a possibly remote user hasn't been written yet but is a logical component to build at some point.  In that case the connector takes care of translating between the message envelope on the CURVE protected connection and the clear messages exchanged "locally".  The clear messages would contain the uid authenticated by the connector though.  Does that make sense?

Regarding capabilities being per broker or per instance, definitely per instance.    If we wanted capabilities to be revokable (or addable) in real time, then mapping uid to capability list in the broker when checking capabilities would be the way to do it, although we would have to be careful not to add latency to this critical path.   I thought a more relaxed capability lookup once at connect time would be sufficient, but maybe not?

> If a user is not in the access list, then connections would be rejected. Otherwise, no capabilities would be assigned to the connection, but the user may be able to perform the basic query options like you describe: list queues, submit work, list details of their own jobs

Yeah that sounds reasonable.  To summarize
* deny connection if user is not in capability db
* allow connection if user is in capability db with a null capability set
* allow some innocuous access if user has a null capability set

**Comment by grondo** [comment]
> The clear messages would contain the uid authenticated by the connector though. Does that make sense?

This seems great. It makes sense that messages within the broker are in the clear since it is all in the same address space anyway. In a module-as-process scenario we might think about encrypting messages to/from processes connected to the broker, if nothing else for message integrity.

> Regarding capabilities being per broker or per instance, definitely per instance. If we wanted capabilities to be revokable (or addable) in real time, then mapping uid to capability list in the broker when checking capabilities would be the way to do it, although we would have to be careful not to add latency to this critical path. I thought a more relaxed capability lookup once at connect time would be sufficient, but maybe not?

No, your choice to have capabilities per connection seems right to me. It also models more closely kernel capabilities, which are per thread, not per user (so user has to login again or spawn new shell to get new capabilities configured by an admin)

**Comment by garlick** [comment]
Thinking about this a bit, possibly the right place to do the capability check is in the message dispatcher of a service's handle.  Then each message handler could be registered with its own capability mask, and the handle could send the EPERM response to denied requests, much like it sends an ENOSYS response to unmatched requests.  That way the general methods like "ping" could be set up to be allowed in services that have otherwise not opted in to multi-user.

**Comment by morrone** [comment]
Capabilites were never ratified as a POSIX standard; they were part of the rejected POSIX.1e standard.  I am not sure how worried we want to be about portability to non-Linux systems, but that might be something to consider before baking into the protocol.

**Comment by grondo** [comment]
> Thinking about this a bit, possibly the right place to do the capability check is in the message dispatcher of a service's handle

That might be useful for some services, but I don't think it should be the *only* place capabilities are checked. For example for a job signaling service, you might want to be able to give certain admin users the CAP_JOB_SIGNAL or whatever capability, but you'd still want to allow a user without this capability to signal their own jobs. If messages without CAP_ADMIN | CAP_JOB_SIGNAL were rejected there'd be no way to accomplish this (I apologize if I'm missing something).

**Comment by grondo** [comment]
>  I am not sure how worried we want to be about portability to non-Linux systems, but that might be something to consider before baking into the protocol.

@morrone, good point. I assumed we're talking about a "capability-like" system just for Flux, but we should avoid pulling in Linux headers or anything to accomplish this. (My guess is that implementation, besides global ACL/Capability registry, would be fairly simple)

**Comment by garlick** [comment]
That's interesting although I would argue not necessarily a problem here, as this proposal is for a design that looks similar to POSIX capabilities, but would not depend on or interact with them.

**Comment by garlick** [comment]
Sorry just deleted my comment re: POSIX as @grondo's comment had been made since my page refreshed.  He and I are in agreement though.

**Comment by garlick** [comment]
> That might be useful for some services, but I don't think it should be the only place capabilities are checked. For example for a job signaling service, you might want to be able to give certain admin users the CAP_JOB_SIGNAL or whatever capability, but you'd still want to allow a user without this capability to signal their own jobs. If messages without CAP_ADMIN | CAP_JOB_SIGNAL were rejected there'd be no way to accomplish this (I apologize if I'm missing something).

Agreed.  If there were a `flux_msg_*()` function for testing a message against a capability mask, then such a check could be done anywhere.  Perhaps all we need for RFC 13 is to capture the "opt in" idea, meaning code doesn't see messages from user != instance owner unless it chooses to enable them.

**Comment by grondo** [comment]
> Perhaps all we need for RFC 13 is to capture the "opt in" idea, meaning code doesn't see messages from user != instance owner unless it chooses to enable them.

Great idea

**Comment by garlick** [comment]
Oops, #74 which updates RFC 3 and 12 got merged without a backref to this issue.

Let's leave this open and discuss next steps a bit.  In flux-framework/flux-core#755 (system instance tracking), the naming of the "privileged helper process" described in the reworked overview of RFC 12.  Should we call it "flux-singularity" in RFC 12 or leave it generic?

We have an unresolved discussion about instances that span administrative domains or at least nodes with inconsistent name-uid mappings.  Last quote from @grondo was

> When starting an instance, the enclosing resource manager (or system in case of a system instance) will resolve user to proper local credentials. When that enclosing RM is Flux, the username to uid resolution can occur in the security shell, which already is required to validate the user based on a global secret or keypair (which probably aren't registered to a UID, but to a global username).

I'm wondering how that affects the userid stamped on every message proposal.  If a user connecting to the broker authenticates as a global username (say kerberos user@realm), then it would seem like we need to pass that identity around in messages so that policy can be consistently implemented (e.g. user@realm submits job so that gets associated with job;  user@realm attempts to cancel job).

I'm not sure what to do then with the local connector that uses SO_PEERCRED auth.  Somehow we would need to map the local uid to a global username.

**Comment by grondo** [comment]
> I'm not sure what to do then with the local connector that uses SO_PEERCRED auth. Somehow we would need to map the local uid to a global username.

Yes, this is the one piece that still references a local UNIX uid. What if instead of SO_PEERCRED (which doesn't work for non-local connectors anyway), users were authenticated with a global credential they'll need to have anyway for job launch?

Perhaps this is per-instance policy, and instances using SO_PEERCRED auth require a consistent uid domain?

**Comment by grondo** [comment]
Can the CURVE keys of the user play any role here? If the CURVE key or similar is the user's token into the Flux system, could this be used to determine user credentials instead of a local UNIX uid? (Thus allowing users to connect to jobs directly from a desktop or other system not in same uid space?

**Comment by garlick** [comment]
> If the CURVE key or similar is the user's token into the Flux system, could this be used to determine user credentials instead of a local UNIX uid? 

Hmm.   Like:
* global (not per instance) userdb maps public CURVE keys to a virtual uid (call it vid)
* config file on every node maps vid to system uid
* per-instance userdb maps vids to roles
* user authenticates to connector using CURVE keypair; gets vid from global userdb, roles from instance userdb
* vid/roles stamped on message by connector, as proposed earlier
* service uses vid/roles to execute policy, as proposed earlier

I think the first bullet leads to significant complexity (something like PKI?).

Did you have something more peer to peer in mind like ssh?

**Comment by garlick** [comment]
I think this is all done.
