### ISSUE TITLE
rfc14: resource count examples do not match resource count definition

### ISSUE THREAD

**Issue by morrone** [flux-framework/rfc#83]
The examples in rfc14 all seem to be using "count" incorrectly in the "resources" sections.  According to the RFC's definition, "count" must be a dictionary that must contain four items: min, max, operator, and operand.  But all of the examples show count being a single integer.

Do we want to change the definition to allow what is shown in the example, or do we want to change the examples to match the definition?

**Comment by grondo** [comment]
This is a good question. Probably true "canonical" jobspec should have `count` as the dictionary as specified, but I wonder if for simplicity the examples could be prefaced with a statement indicating that, in the examples, if `count` is a value not a dictionary, then that implies

```yaml
count:
  - min: value
  - max: value
  - operator: "+"
  - operand: 1
```

(sorry if I got `operand` form incorrect)

I think this would be unrealistically verbose to write out for all examples, but I could be convinced otherwise.

**Comment by morrone** [comment]
I think if it needs to be verbose to meet the spec, then we should suck it up and be verbose in our documentation.  It makes it too hard to understand the documentation if the reader needs to be mentally inserting substitutions in a number of places.  If we can't spare the extra characters in our document, then maybe we shouldn't be forcing that verbosity on our users. :)

**Comment by grondo** [comment]
Good points, however it is expected that real world jobspec would have all kinds of shorthand that a jobspec parser or compiler would translate into canonical jobspec, e.g. `count: "[min:max:operand:operator]"`, and so on... @trws even had some proposals for single-line versions of some of this stuff. So hopefully we won't be foisting the verbose spec on our users.

But you make a good point about making the document rigorous, so I think you're right about sucking it up...

**Comment by morrone** [comment]
I think that a dictionary in YAML works like this:

```
count:
  min: value
  max: value
  operator: "+"
  operand: 1
```

On the topic of "operator", perhaps it would be better to use words like "add", "multiply", etc. rather than symbols?  Or at the very least we need to document our symbols.  I don't know what "^" means.  Bitwise xor probably isn't a useful operand as far as I can tell. :)  So maybe it is the power operator.

**Comment by grondo** [comment]
ah, ok I'm a terrible YAML generator...

**Comment by morrone** [comment]
> Good points, however it is expected that real world jobspec would have all kinds of shorthand

What do you mean by "real world jobspec"?  Is that something that flux provides, or something else?  If it is part of flux, then are we going to have two different rfc specs for essentially the same thing?  That seems like more work to have multiple parsers than remeber which we are working with at what time rather than just making the spec a little more complicated (to be more user-friendly) and implement it once...

**Comment by grondo** [comment]
I think the idea was that the user-facing commands would take something reasonable, and generate "canonical" jobspec so that backend users (like a scheduler) wouldn't have to deal with many specs.
(analogy: assembly is to programming languages as jobspec is to ...)

E.g. `flux run -N 4 -n 4 ...` might generate the relevant canonical spec to pass to the current instance. Having a canonical jobspec will allow us to make testsuites that ensure front end jobspec compilers generate valid output.

I do agree that we could make the spec just a little more complex and remove some of the more onerously verbose requirements of the canonical version. The tradeoff is every user of the spec would have a lot of code like

```
if count is a value then
  min = max = count
else if count is a dictionary then
  min = count.min
  max = count.max
  ...
endif
```

Though I suppose that could be hidden in the library, in which case I'm all for your suggestions.

**Comment by morrone** [comment]
Mmm, but your example is a command line interface, not a separate jobspec.  The question, I think is what format we present to users.  Users that need more that the command line interface supplies will have to use _some_ jobspec.  Is that the simple, verbose spec of rfc14?  Or is that going to be yet another "real world" jobspec?  I would rather not have two different spec formats built into flux.

**Comment by trws** [comment]
That is how a dictionary is formatted in yaml, or like JSON with the curly braces.

The ^ is meant to be power or exponent, taking words seems reasonable.

When I was designing the dense interface, it was designed to be jobspec, but with rules to reduce verbosity based on value types. For example. A scalar value where a resource is expected was interpreted as a string with a syntax that could express basic trees that, when canonicalized, would become jobspec. By the same token, if a count takes a scalar rather than a dict, it expands to min and max are equal to that scalar. For example:

Node>Core[2]

Was a scalar that interpreted in resource position would expand to: (on phone, formatting may suffer)

resources:
  type : Node
  count: 1
  with:
    type: Core
    count: 2

It was meant to allow dense to be mixed into canonical by the user, but then canonicalized for use by the rest of the system.


---
Sent from Boxer | http://getboxer.com<http://bxr.io/PBI3C>

On March 21, 2017 at 7:14:51 PM EDT, Christopher J. Morrone <notifications@github.com> wrote:

Mmm, but your example is a command line interface, not a separate jobspec. The question, I think is what format we present to users. Users that need more that the command line interface supplies will have to use some jobspec. Is that the simple, verbose spec of rfc14? Or is that going to be yet another "real world" jobspec? I would rather not have two different spec formats built into flux.

**Comment by morrone** [comment]
I'm not a fan of implementing two jobspec formats, one dense and one canonical.  It seems like more work than necessary.  If we write a parser that can handle "dense" and convert it into an in-memory representation, why bother implementing a second parser that can only do "canonical".  And if we have just one parser library that we can reuse, there doesn't seem to be any point to do a conversion to the canonical form at any point in the process.

**Comment by trws** [comment]
There isn't really, the canonical version happened to allow us to 
specify it with a subset of the complexity.  The dense version is, in my 
personal opinion, nice but vastly more complex.
